all:
  hosts:
    192.168.120.131:
      ansible_user: jenkins
      ansible_become: true
      ansible_become_method: sudo
      ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/id_rsa
     # ansible_become_password: "190770911"
    #  ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      
     
     
      

